
// Data
export const INITIAL_INTENTS = [
    {
        id: 1,
        name: 'greeting',
        displayName: 'Greeting',
        category: 'General',
        trainingPhrases: 12,
        responses: 3,
        usage: 1250,
        confidence: 98,
        status: 'Active',
        lastModified: '2023-10-15',
        description: 'Handles user greetings like hello, hi, etc.'
    },
    {
        id: 2,
        name: 'check_balance',
        displayName: 'Check Balance',
        category: 'Account',
        trainingPhrases: 25,
        responses: 2,
        usage: 850,
        confidence: 92,
        status: 'Active',
        lastModified: '2023-10-14',
        description: 'Allows users to check their current account balance.'
    },
    {
        id: 3,
        name: 'transfer_funds',
        displayName: 'Transfer Funds',
        category: 'Payments',
        trainingPhrases: 40,
        responses: 5,
        usage: 600,
        confidence: 88,
        status: 'Inactive',
        lastModified: '2023-10-10',
        description: 'Initiates a fund transfer process between accounts.'
    },
    {
        id: 4,
        name: 'support_contact',
        displayName: 'Contact Support',
        category: 'Support',
        trainingPhrases: 15,
        responses: 1,
        usage: 300,
        confidence: 95,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides contact information for customer support.'
    },{
        id: 5,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 6,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 7,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 8,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 9,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 10,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 11,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 12,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 13,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 14,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 15,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 16,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 17,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 18,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 19,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 20,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 21,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    },{
        id: 22,
        name: 'contact',
        displayName: 'Contact',
        category: 'Support',
        trainingPhrases: 5,
        responses: 1,
        usage: 320,
        confidence: 96,
        status: 'Active',
        lastModified: '2023-10-12',
        description: 'Provides information for customer support.'
    }
];